const pluginSecurity = require('eslint-plugin-security');

module.exports = [
  pluginSecurity.configs.recommended,
  {
    ignores: [
      'node_modules/**',
      'public/js/chart.umd.js',
      'tests/**',
      'coverage/**'
    ],
  },
  {
    files: ['server.js', 'eslint.config.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        console: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'security/detect-object-injection': 'warn',
      'security/detect-non-literal-require': 'warn',
      'security/detect-non-literal-fs-filename': 'warn',
      'security/detect-possible-timing-attacks': 'warn',
    },
  },
  {
    files: ['public/js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        fetch: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        Chart: 'readonly',
        API_BASE: 'writable',
        getCsrfToken: 'writable',
        isAuthenticated: 'writable',
        updateAuthUI: 'writable',
        handleLoginSubmit: 'writable',
        handleLogout: 'writable',
        togglePasswordVisibility: 'writable',
        showToast: 'writable',
        showPage: 'writable',
        debouncedUpdateCalc: 'writable',
        updateCalc: 'writable',
        updateDailyLogsUI: 'writable',
        saveDailyLog: 'writable',
        getDailyLogs: 'writable',
        updateWeeklyChartFromLogs: 'writable',
        habits: 'writable',
        toggleHabit: 'writable',
        emissions: 'writable',
        module: 'writable',
        exports: 'writable',
      },
    },
    rules: {
      'no-console': 'off',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'security/detect-object-injection': 'off',
    },
  },
];
